# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

complete_lambda <- function(orig_chol_mat, current_G, p, cores) {
    .Call(`_bayesWatch_complete_lambda`, orig_chol_mat, current_G, p, cores)
}

DRJ_MCMC_singlestep <- function(current_lambda, lambda_0, current_G, p, cores, edge_updated_i, edge_updated_j, scale_matrix, n_regime, mean_vector_regime, nS2, b, spread_parameter_sd2, mean_hyperparameter, lambda_hyperparameter, g_prior) {
    .Call(`_bayesWatch_DRJ_MCMC_singlestep`, current_lambda, lambda_0, current_G, p, cores, edge_updated_i, edge_updated_j, scale_matrix, n_regime, mean_vector_regime, nS2, b, spread_parameter_sd2, mean_hyperparameter, lambda_hyperparameter, g_prior)
}

log_dNormalWishart_posterior_unnormalized <- function(data_matrix, m_hyperparameter, scale_matrix, lambda_hyperparameter, nu_wishartDF, observed_mu, observed_precision) {
    .Call(`_bayesWatch_log_dNormalWishart_posterior_unnormalized`, data_matrix, m_hyperparameter, scale_matrix, lambda_hyperparameter, nu_wishartDF, observed_mu, observed_precision)
}

log_dNormalWishart_unnormalized <- function(m_hyperparameter, posterior_inv_scale, lambda_hyperparameter, nu_wishartDF, observed_mu, observed_precision) {
    .Call(`_bayesWatch_log_dNormalWishart_unnormalized`, m_hyperparameter, posterior_inv_scale, lambda_hyperparameter, nu_wishartDF, observed_mu, observed_precision)
}

rmu_0 <- function(sigma_0, sum_precision_matrices, sum_precision_times_mu, m_hyperparameter) {
    .Call(`_bayesWatch_rmu_0`, sigma_0, sum_precision_matrices, sum_precision_times_mu, m_hyperparameter)
}

log_MH_Gupdate_Rcpp <- function(selected_edge_i, selected_edge_j, oldG, newG, oldK, newK, b, p) {
    .Call(`_bayesWatch_log_MH_Gupdate_Rcpp`, selected_edge_i, selected_edge_j, oldG, newG, oldK, newK, b, p)
}

log_MH_mergesplit_Rcpp <- function(oldK, newK, b, p) {
    .Call(`_bayesWatch_log_MH_mergesplit_Rcpp`, oldK, newK, b, p)
}

log_transition_probability_HMM_Rcpp <- function(transition_probabilities, my_states, length_of_vector) {
    .Call(`_bayesWatch_log_transition_probability_HMM_Rcpp`, transition_probabilities, my_states, length_of_vector)
}

select_edge_from_G_prior_Rcpp <- function(G, g_prior, p) {
    .Call(`_bayesWatch_select_edge_from_G_prior_Rcpp`, G, g_prior, p)
}

log_dmvnrm_arma_regular <- function(data_x, mean, prec) {
    .Call(`_bayesWatch_log_dmvnrm_arma_regular`, data_x, mean, prec)
}

redraw_Z_arma <- function(current_data, current_precision, current_mu, p, lower_bounds, upper_bounds, lower_bound_is_equal, upper_bound_is_equal, is_missing, is_continuous, raw_data, cores) {
    .Call(`_bayesWatch_redraw_Z_arma`, current_data, current_precision, current_mu, p, lower_bounds, upper_bounds, lower_bound_is_equal, upper_bound_is_equal, is_missing, is_continuous, raw_data, cores)
}

redraw_Z_arma_justmissings <- function(current_data, current_precision, current_mu, p, lower_bounds, upper_bounds, lower_bound_is_equal, upper_bound_is_equal, is_missing, is_continuous, cores) {
    .Call(`_bayesWatch_redraw_Z_arma_justmissings`, current_data, current_precision, current_mu, p, lower_bounds, upper_bounds, lower_bound_is_equal, upper_bound_is_equal, is_missing, is_continuous, cores)
}

get_justmissings_density <- function(current_data, current_precision, current_mu, p, lower_bounds, upper_bounds, lower_bound_is_equal, upper_bound_is_equal, is_missing, is_continuous, cores) {
    .Call(`_bayesWatch_get_justmissings_density`, current_data, current_precision, current_mu, p, lower_bounds, upper_bounds, lower_bound_is_equal, upper_bound_is_equal, is_missing, is_continuous, cores)
}

log_normalizing_g_wishart_posterior_laplace <- function(graph, D_post, Delta, n, p) {
    .Call(`_bayesWatch_log_normalizing_g_wishart_posterior_laplace`, graph, D_post, Delta, n, p)
}

calc_logprob_Gibbs_comp <- function(current_precision, current_mu, regime_comp_log_probs, current_data, proposed_component) {
    .Call(`_bayesWatch_calc_logprob_Gibbs_comp`, current_precision, current_mu, regime_comp_log_probs, current_data, proposed_component)
}

gibbs_swap_btwn_two <- function(first_precision, second_precision, first_mu, second_mu, component_log_probs, indices_of_split_component, data_points_of_state, assignments_launch, first_component, second_component, num_gibbs_sweeps) {
    .Call(`_bayesWatch_gibbs_swap_btwn_two`, first_precision, second_precision, first_mu, second_mu, component_log_probs, indices_of_split_component, data_points_of_state, assignments_launch, first_component, second_component, num_gibbs_sweeps)
}

gibbs_swap_comps <- function(data_points_of_state, cluster_assignments, regime_comp_log_probs, precisions, mus, assignments_maximum, gibbs_sweeps) {
    .Call(`_bayesWatch_gibbs_swap_comps`, data_points_of_state, cluster_assignments, regime_comp_log_probs, precisions, mus, assignments_maximum, gibbs_sweeps)
}

rmvn_Rcpp <- function(mus, K, p) {
    .Call(`_bayesWatch_rmvn_Rcpp`, mus, K, p)
}

rwish_Rcpp <- function(Ts, b, p) {
    .Call(`_bayesWatch_rwish_Rcpp`, Ts, b, p)
}

rgwish_Rcpp <- function(G, D, b, p, threshold) {
    .Call(`_bayesWatch_rgwish_Rcpp`, G, D, b, p, threshold)
}

log_wishart_normalizingConstant_mc_Rcpp <- function(G, nu, b, H, check_H, mc_iters, p) {
    .Call(`_bayesWatch_log_wishart_normalizingConstant_mc_Rcpp`, G, nu, b, H, check_H, mc_iters, p)
}

